### ISSUE TITLE
TypeScript error in 0.17.0

### ISSUE THREAD

**Issue by mikeobrien** [aurelia/bootstrapper#19]
Getting this TypeScript error after upgrading to 0.17.0:

``` bash
.../jspm_packages/github/aurelia/bootstrapper@0.17.0/aurelia-bootstrapper.d.ts(4,10): 
error TS1192: Module '"core-js"' has no default export.
```

Looks like this is a regression might be related to aurelia/framework/issues/177?

**Comment by mikeobrien** [comment]
Related aurelia/framework/issues/202
