### ISSUE TITLE
error in 0.18.0

### ISSUE THREAD

**Issue by ashirai** [aurelia/bootstrapper#22]
After upgrading aurelia-bootstrapper to 0.18.0, I am getting this error: `Unhandled promise rejection TypeError: this.metadata.initialize is not a function`. Any idea? I upgraded all other plugins for Oct 13th release (except aurelia-http-client since this is also throwing a different error `Unhandled promise rejection TypeError: _this.XHRType is not a function`)

**Comment by EisenbergEffect** [comment]
It sounds like you have some version forks. Check your config.js.

**Comment by plwalters** [comment]
Feel free to drop by our official gitter - gitter.im/aurelia/discuss in case you are still having issues someone is usually around to help with these kinds of issues.
